"""
English + Roman Urdu question templates for chatbot battery runs.
Placeholders: P1 P2 P3, D1 D2 D3, S1 S2, M1 M2 (projects, developers, skills, task/topic phrases).
All data is injected from Mongo at runtime — no hardcoded team names in this file.
"""

EN_FORMS: list[str] = [
    "What are my assigned tasks?",
    "Show my pending tasks.",
    "List all my tasks with status.",
    "What is my next deadline?",
    "What should I do today?",
    "What do I do today?",
    "What skills do I have?",
    "What are my skills?",
    "Do I have enough skills for {S1} work?",
    "What is the status of {P1}?",
    "What is the status of the {P1} project?",
    "Give me a quick summary of {P1}.",
    "Quick summary for {P1}",
    "What is the deadline for {P1}?",
    "Who created {P1}?",
    "How many tasks are on {P1}?",
    "How many tasks are on the {P1} project?",
    "How many open tasks are on {P1}?",
    "Open tasks on {P1}",
    "Who is working on {P1}?",
    "Who works on {P1}?",
    "List team members for {P1}.",
    "Team members for {P1}",
    "Is {D1} on the {P1} team?",
    "Is {D1} part of the {P1} project team?",
    "Who is responsible for {M1} on {P1}?",
    "Who handles the API integration for {P1}?",
    "Who handles {M1} for {P1}?",
    "What skills does {D1} have?",
    "Which developer knows {S1}?",
    "Who knows {S1}?",
    "Who has {S1} skill?",
    "Does {D1} have a {M1} task?",
    "Does {D1} have an {S1} related task?",
    "Did {D1} complete {M1}?",
    "Is {D1} doing {M1}?",
    "Has {D1} been assigned {M1}?",
    "Is {D2} working on {M1}?",
    "Does {D2} have a {S2} task assigned?",
    "What is the status of {P2}?",
    "Who created {P2}?",
    "How many tasks are on {P2}?",
    "Who is working on {P2}?",
    "Overall, how are all our projects going?",
    "What is overall project performance?",
    "List running projects",
    "Show running projects",
    "Who is the most active developer?",
    "Who has completed the most tasks?",
    "Which developer completed the most tasks?",
    "What is {D1} working on right now?",
    "What projects is {D1} assigned to?",
    "Tell me open tasks in the {P1} project",
    "Any open tasks on {P1}?",
    "Who should I contact about {M1} on {P1}?",
    "Is there a deadline for {P2}?",
    "Compare workload for {D1} and {D2}",
    "Does {D3} know {S1}?",
    "Who on the team knows {S2}?",
    "Project health snapshot for {P1}",
    "Task progress for {P1}",
    "Who owns testing on {P1}?",
    "Who owns UI work on {P1}?",
    "Is {P1} behind schedule?",
    "How is {P2} going?",
    "List tasks related to {S1}",
    "Who is least busy among developers?",
    "Show developers with {S1} on profile",
    "Does {P1} need more backend help?",
    "Summarize {P2} in one screen",
    "Who created {P3}?",
    "How many developers are on {P1}?",
    "Is {M2} still open on {P1}?",
    "Who completed {M2} on {P1}?",
    "Is {D1} available for new tasks?",
    "What is {D2}'s next deadline?",
    "Any blockers on {P1}?",
    "List completed tasks on {P1}",
    "Who submitted work on {M1}?",
    "Routing: who picks up {S2} tasks?",
    "Skill match: {D1} vs {S1} requirements",
    "Should we assign {M1} to {D2}?",
    "Who is faster on {S1}, {D1} or {D2}?",
    "Cross-check: {D3} and {M2}",
    "Verify team for {P3}",
    "Headcount on {P2}",
    "Active vs done tasks on {P1}",
    "Who has the lightest load?",
    "Who has the heaviest load?",
    "Jury question: status of {P1}?",
    "Jury question: who built {P2}?",
    "Explain {P1} timeline",
    "Risk: is {P1} at risk?",
    "Milestone check for {P2}",
]

UR_FORMS: list[str] = [
    "Mere assigned tasks kya hain?",
    "Mere pending tasks dikhao.",
    "Meri saari tasks status ke sath batao.",
    "Mera next deadline kya hai?",
    "Aaj mujhe kya karna chahiye?",
    "Meri skills kya hain?",
    "Kya mere paas {S1} ke liye skills kaafi hain?",
    "{P1} ka status kya hai?",
    "{P1} ka short summary batao.",
    "{P1} ki deadline kab hai?",
    "{P1} kis ne banaya?",
    "{P1} par kitne tasks hain?",
    "{P1} par kitne open tasks hain?",
    "{P1} par kon kaam kar raha hai?",
    "{P1} ki team members kon kon hain?",
    "{P1} ke team members list karo.",
    "Kya {D1} {P1} team me hai?",
    "{P1} par {M1} kis ke paas hai?",
    "{P1} me API integration kon kar raha hai?",
    "{D1} ki skills kya hain?",
    "Kis developer ko {S1} skill hai?",
    "Kis developer ko {S2} aati hai?",
    "Saare projects ka overall scene kaisa hai?",
    "Overall project performance kaisi hai?",
    "Running projects dikhao.",
    "Sab se zyada active developer kon hai?",
    "Sab se zyada tasks kis ne complete kiye hain?",
    "{P2} ka status kya hai?",
    "{P2} par kitne tasks hain?",
    "{P2} par kon kaam kar raha hai?",
    "Kya {D2} {P2} team me hai?",
    "{P2} ki deadline kab hai?",
    "{P3} kis ne banaya?",
    "Kya {D1} ne {M1} complete kiya?",
    "Kya {D2} ke paas {M1} task hai?",
    "Kya {D3} {M2} handle kar raha hai?",
    "{D1} {S1} janta hai kya?",
    "{P1} py {M2} kon kar raha hai?",
    "{P1} summary jaldi batao.",
    "{P1} ka health kaisa hai?",
    "Open tasks {P1} me kitni hain?",
    "Kitne tasks complete ho chuke {P1} me?",
    "{D1} busy hai kya?",
    "{D1} ka workload kaisa hai?",
    "Testing ka task {P1} par kon kar raha hai?",
    "UI design {P1} par kis ke paas hai?",
    "Figma task {D1} ke paas hai kya?",
    "Kya {D2} ne Figma design task kiya?",
    "Kya {D1} ko {M1} assign hai?",
    "Next deadline {D2} ki kya hai?",
    "Sab projects list karo.",
    "Hamare projects ka haal batao.",
    "Kon kon {P1} py laga hua hai?",
    "Kaun kaun {P2} team me hai?",
    "{P1} par backend kon kar raha hai?",
    "{P1} par frontend kon kar raha hai?",
    "MongoDB skill kis developer ko hai?",
    "FastAPI kis ko aata hai?",
    "React experts kon kon hain?",
    "Project {P3} ka status kya hai?",
    "{P2} me kitne bande hain?",
    "Kya {P1} delay par hai?",
    "Mujhe {P1} ka overview chahiye.",
    "Jury ke liye: {P1} summary.",
    "Viva: {P1} team kon?",
    "{D1} aur {D2} me se zyada load kis par hai?",
    "{M1} abhi kis ke naam pe hai?",
    "{M2} complete ho gaya kya?",
    "Kya {D3} {P1} me assign hai?",
    "Skills check: {D1} ke paas {S2} hai?",
    "Roman Urdu: {P1} py kaam kon?",
    "Hinglish: {P2} status batao na.",
    "Bhai {P1} deadline extend hui?",
    "{P1} par active tasks batao.",
    "Done tasks {P1} me kon kon ne kiye?",
    "Assignee list for {P1}",
    "PM ne {P2} banaya tha kya?",
    "Kis bande ne {P3} create kiya?",
    "Team roster {P1}",
    "Roster {P2} ka batao.",
    "Kya {D1} ne {M2} submit kiya?",
    "Abhi {M1} kis ke queue me hai?",
    "Skill gap {P1} ke liye kya hai?",
    "Training kis ko chahiye {S1} me?",
    "Recommend developer for {S2}",
    "Best match {S1} ke liye kon?",
    "Load balancing: {D1} vs {D3}",
    "Kaun fastest hai {S1} me?",
    "Project priority: {P1} ya {P2}?",
    "Sync: {P1} tasks kitne open?",
    "Daily standup style: {D1} kya kar raha?",
    "Blocker hai {P1} par?",
    "Unblock ke liye kon contact?",
    "Handoff: {M1} kis ko dena chahiye?",
    "Code review task kis ke paas?",
    "Documentation task kon lega?",
    "Deployment step kis ne kiya?",
    "Bug fix queue me kon hai?",
    "QA signoff kis ne diya?",
    "Staging deploy kis bande ne kiya?",
    "Production ready hai {P1}?",
    "Sprint goal {P2} achieve hua?",
    "Velocity {P1} ki kaisi hai?",
    "Burndown nahi pooch raha, sirf status: {P1}",
    "Plain question: {P1} ka kya scene?",
    "Short answer chahiye: {P2} deadline?",
    "One line: {D1} free hai?",
    "Yes/No: {D2} {M1} pe hai?",
    "Confirm: {D3} {P1} team me?",
    "Double check: {S1} kis ko aata hai?",
    "Triple check: {P2} tasks total?",
    "Final: most active developer kon?",
    "Last: sab se zyada complete tasks kis ke?",
]
