from docx import Document


def add_paragraphs(doc: Document, lines: list[str]) -> None:
    for line in lines:
        if not line.strip():
            doc.add_paragraph("")
            continue
        if line.startswith("- "):
            doc.add_paragraph(line[2:], style="List Bullet")
            continue
        doc.add_paragraph(line)


def main() -> None:
    doc = Document()
    doc.add_heading("Skill Mapping Platform Backend - Code Explanation", level=0)
    doc.add_paragraph("Generated by assistant. File paths below match the current repository contents.")

    doc.add_heading("1) App Startup and Routing", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/main.py` creates the FastAPI application and registers all routers.",
            "",
            "Key parts:",
            "- A FastAPI app instance is created with `title`, `description`, and `version`. Custom `/docs` and `/redoc` are registered; `/` redirects to Swagger.",
            "- On startup (`@app.on_event('startup')`), it calls `db.connect()` to connect to MongoDB.",
            "- On shutdown (`@app.on_event('shutdown')`), it calls `db.disconnect()`.",
            "- `StripApiPrefixMiddleware` strips a leading `/api` from paths so clients can call either `/projects/...` or `/api/projects/...` (matches Vite proxy and direct API use).",
            "- `CORSMiddleware` uses `settings.CORS_ORIGINS` plus `allow_origin_regex` for LAN IPs when Vite uses `host: true`.",
            "- Routers are registered in this order:",
            "  - `auth`, `users`",
            "  - `projects.team_details_router` under prefix `/projects` (must be before generic `GET /projects/{project_id}`)",
            "  - `projects.router`",
            "  - `tasks`, `teams`, `analytics`, `chatbot`, `recommendation_flow`, `ml`",
        ],
    )

    doc.add_heading("2) Configuration", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/config.py` defines `Settings` (a `pydantic_settings.BaseSettings`) and loads environment variables via `load_dotenv()`.",
            "",
            "Important settings used by the code:",
            "- MongoDB:",
            "  - `MONGODB_URL` (default: `mongodb://localhost:27017`)",
            "  - `MONGODB_DB_NAME` (default: `skill_mapping`)",
            "- JWT auth:",
            "  - `SECRET_KEY` (default is placeholder text; must be changed in production)",
            "  - `ALGORITHM` (`HS256`)",
            "  - `ACCESS_TOKEN_EXPIRE_MINUTES` (defaults to 7 days)",
            "- Uploads:",
            "  - `UPLOAD_DIR` (default: `./uploads`)",
            "  - `MAX_FILE_SIZE` (10MB)",
            "  - `ALLOWED_EXTENSIONS` (default: `.pdf`, `.doc`, `.docx`, `.txt`)",
            "- ML model / NLP:",
            "  - `SPACY_MODEL` default `en_core_web_sm`",
        ],
    )

    doc.add_heading("3) Database Layer (MongoDB)", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/database.py` contains the MongoDB connection and per-collection helpers.",
            "",
            "Key behavior:",
            "- `Database.connect()` creates an `AsyncIOMotorClient(settings.MONGODB_URL)`.",
            "- It selects the DB: `self.client[settings.MONGODB_DB_NAME]`.",
            "- `get_collection(name)` returns `self.db[name]`.",
            "",
            "Collection helper functions:",
            "- `get_users_collection()` -> `users`",
            "- `get_projects_collection()` -> `projects`",
            "- `get_tasks_collection()` -> `tasks`",
            "- `get_skills_collection()` -> `skills`",
            "- `get_documents_collection()` -> `srs_documents`",
        ],
    )

    doc.add_heading("4) Data Models", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/models/user.py` defines user-related request/response schemas and JWT container types.",
            "",
            "User model highlights (`user.py`):",
            "- `UserBase` fields:",
            "  - `email` (uses `EmailStr`)",
            "  - `username`",
            "  - `full_name` (optional)",
            "  - `skills` (list of strings; default is `[]`)",
            "  - `role` default `user`",
            "- `UserCreate` adds `password`.",
            "- `UserUpdate` allows optional updates (`username`, `full_name`, `skills`, `role`).",
            "- `UserResponse` adds `id`, `created_at`, `updated_at`.",
            "- `LoginRequest` contains `email` and `password`.",
            "- `Token` returns JWT plus `token_type` and the `user` response.",
            "",
            "`backend/app/models/project.py` defines project schemas used by the `/projects` endpoints.",
            "",
            "Project model highlights (`project.py`):",
            "- `ProjectBase` fields:",
            "  - `title`, `description`",
            "  - `require_skills` (list of strings)",
            "  - `deadline` (datetime)",
            "  - `department`",
            "  - `status` constrained by regex pattern (`planning|in_progress|completed|on_hold`)",
            "  - `progress` (0-100)",
            "  - `team_size`",
            "- `ProjectCreate` adds:",
            "  - `created_by`",
            "  - `srs_document` (optional path)",
            "- `ProjectResponse` adds:",
            "  - `id`, `created_by`, `assigned_team`, `created_at`, `updated_at`",
            "- Recommendation response model:",
            "  - `DeveloperRecommendation` and `ProjectRecommendations`",
        ],
    )

    doc.add_heading("5) Authentication and Security", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/core/security.py` implements password hashing and JWT encode/decode.",
            "",
            "Security logic:",
            "- Uses `passlib.context.CryptContext` with scheme `bcrypt`.",
            "- `get_password_hash(password)` -> bcrypt hash.",
            "- `verify_password(plain_password, hashed_password)` -> boolean.",
            "- `create_access_token(data, expires_delta)`:",
            "  - copies `data`",
            "  - sets `exp` (expiration) claim",
            "  - encodes JWT with `settings.SECRET_KEY` and `HS256`.",
            "- `decode_token(token)` decodes JWT, extracts:",
            "  - `sub` -> email",
            "  - `user_id`",
            "  - `role`",
            "  - returns `TokenData` or `None` if invalid.",
        ],
    )

    add_paragraphs(
        doc,
        [
            "",
            "`backend/app/routes/auth.py` defines the authentication endpoints and dependency.",
            "",
            "Routes and dependency:",
            "- Dependency `get_current_user` uses `OAuth2PasswordBearer` to read the `Authorization: Bearer <token>` header.",
            "- It calls `decode_token(token)` and then queries MongoDB (`users` collection) by `email`.",
            "- It converts Mongo `_id` into a string `id` for the response.",
            "",
            "Endpoints:",
            "- `POST /auth/register` (`register`) : creates a user document in MongoDB with `hashed_password` plus timestamps.",
            "  - Rejects duplicate emails (400).",
            "  - Default role is set to `developer` if role is missing/empty.",
            "  - Returns a JWT token and the created user.",
            "- `POST /auth/login` (`login`) : verifies password and returns JWT + user.",
            "- `GET /auth/me` (`read_users_me`) : returns the authenticated user from the dependency.",
        ],
    )

    doc.add_heading("6) User Routes", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/users.py` registers endpoints under `/users`.",
            "",
            "Endpoints:",
            "- `GET /users/developers` returns all users where `role == 'developer'`.",
            "- `PUT /users/{user_id}` updates user profile info.",
            "  - Allowed if `user_id == current_user.id` OR `current_user.role == 'manager'`.",
            "  - Performs `update_one` and then fetches updated doc for the response.",
            "- `POST /users/{user_id}/skills` updates a user’s `skills` list from input objects containing `skill_name`.",
        ],
    )

    doc.add_heading("7) Project Routes", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/projects.py` registers endpoints under `/projects`.",
            "",
            "Endpoints:",
            "- `POST /projects/` (`create_project`):",
            "  - Accepts form fields via `Form(...)` (title, description, deadline, department, require_skills).",
            "  - `require_skills` is split by comma into a list.",
            "  - Accepts optional `srs_document` upload.",
            "  - If an SRS document is uploaded, it is saved, parsed by `DocumentParser.parse_srs_document`, and the parsed title/description/detected skills/complexity are merged into the project data.",
            "  - Inserts the project into MongoDB and returns a `ProjectResponse`.",
            "- `GET /projects/` (`get_projects`): supports pagination (`skip`, `limit`) and optional `status` filter.",
            "  - If `current_user.role == 'developer'`, it filters using `assigned_team` = current user id.",
            "  - If `current_user.role == 'manager'`, it filters using `created_by` = current user id.",
            "- `GET /projects/{project_id}` returns a single project by id.",
            "- `PUT /projects/{project_id}` updates a project with permission checks similar to user updates.",
            "- `GET /projects/{project_id}/recommendations` returns recommendations computed by `SkillMatcher.get_recommendations`.",
            "  - Restricted to managers.",
            "- Team-detail and related routes live on `projects.team_details_router` (registered first under `/projects`) so paths like `team-details` are not mistaken for Mongo `ObjectId`s.",
        ],
    )

    doc.add_heading("8) Task Routes", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/tasks.py` registers endpoints under `/tasks` (workflow: assigned → in_progress → submitted → completed).",
            "",
            "Main endpoints:",
            "- `GET /tasks/` — list tasks visible to the caller (role-aware filters, optional `status`, `project_id`).",
            "- `POST /tasks/` — create task (managers/admins; enforces workload limits and project access).",
            "- `GET /tasks/review-submissions` — PM review queue for submitted tasks.",
            "- `POST /tasks/{task_id}/submit-for-review` — developer submits work (optional file attachments).",
            "- `POST /tasks/{task_id}/request-changes` — PM sends task back for revision.",
            "- `GET /tasks/{task_id}/submission/file/{file_index}` — download an attached submission file.",
            "- `PUT /tasks/{task_id}/status` — status transitions; **only managers/admins may set `completed`** after review.",
            "",
            "Adaptive skills on completion:",
            "- When status becomes **`completed`**, the handler bumps the assignee’s **`skills`** proficiency for each entry in the task’s **`skills_used`** list (capped), with optional activity bonus; see the `new_status == \"completed\"` branch in this file.",
        ],
    )

    doc.add_heading("9) ML / Document Parsing Routes", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/ml.py` registers endpoints under `/ml`.",
            "",
            "Endpoints:",
            "- `POST /ml/parse-srs` :",
            "  - Validates uploaded extension against `settings.ALLOWED_EXTENSIONS`.",
            "  - Saves upload to `UPLOAD_DIR/temp` (using `save_uploaded_file`).",
            "  - Parses the file using `DocumentParser.parse_srs_document`.",
            "  - Deletes the temporary file.",
            "  - Returns parsed content plus a time-line suggestion derived from `complexity_score`.",
            "- `POST /ml/match-developers` :",
            "  - Manager-only endpoint.",
            "  - Finds developers where `role == 'developer'` and `availability == True`.",
            "  - Scores each developer via `SkillMatcher.match_developer_to_project` and returns matches over `min_match_score`.",
            "- `GET /ml/skill-analysis` :",
            "  - Manager-only endpoint.",
            "  - Compares a project’s `require_skills` against currently assigned team members’ `skills`.",
            "  - Returns covered/missing skills, coverage percentage, and up to 5 suggested developers to cover missing skills.",
        ],
    )

    doc.add_heading("10) Document Parsing Logic", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/core/document_parser.py` implements `DocumentParser`.",
            "",
            "spaCy behavior:",
            "- `_load_spacy_nlp()` tries to import spaCy and load `settings.SPACY_MODEL`.",
            "- If loading fails for any reason, it returns `None`.",
            "- `DocumentParser.__init__()` stores this in `self.nlp`.",
            "",
            "Supported input types:",
            "- `.pdf` via `pdfplumber` text extraction (plus OCR for embedded images using `pytesseract`).",
            "- `.docx` via `python-docx` paragraph/table extraction.",
            "- `.doc` currently falls back to plain text (`parse_txt`).",
            "- `.txt` via UTF-8 file read.",
            "",
            "Requirement extraction:",
            "- `extract_requirements(text)` builds:",
            "  - `title` from the first non-empty line longer than 10 characters",
            "  - `description` from the first up to 3 sentences",
            "  - `detected_skills` using substring match against a built-in `technical_skills` dictionary",
            "  - `timeline_indicators` using keyword matches in sentences",
            "  - `complexity_score` computed from word count, number of detected skills, and sentence count",
            "  - `team_size_suggestion` (3 if complexity > 70, 2 if > 40, else 1)",
            "",
            "Top-level API:",
            "- `parse_srs_document(file_path)` selects the parser by extension, raises errors if no text is extracted, and returns:",
            "  - `extracted_text` (first 5000 characters)",
            "  - `requirements` object",
            "  - `file_metadata` (path, size, extension)",
        ],
    )

    doc.add_heading("11) Skill Matching Logic", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/core/skill_matcher.py` implements `SkillMatcher` for recommendation scoring.",
            "",
            "Approach:",
            "- Uses a `TfidfVectorizer` configured with character n-grams (`analyzer='char_wb'`, `ngram_range=(3,5)`).",
            "- Similarity is computed using cosine similarity between TF-IDF vectors.",
            "",
            "Scoring functions:",
            "- `calculate_skill_similarity(required_skills, developer_skills)`:",
            "  - fits TF-IDF on (required + developer skills)",
            "  - compares each required entry against developer entries",
            "  - returns the mean of best similarities.",
            "- `calculate_experience_match(project_complexity, developer_experience)`:",
            "  - returns 1.0 if experience >= complexity else a ratio.",
            "- `calculate_availability_score(developer_availability, current_workload)`:",
            "  - returns 0 if unavailable; otherwise subtracts a penalty capped at 0.5.",
            "- `calculate_cgpa_score(cgpa)`:",
            "  - assumes 0-4 scale and normalizes to 0-1.",
            "- `calculate_performance_score(performance_history)`:",
            "  - weights recent performance higher and normalizes to 0-1.",
            "",
            "Developer -> Project matching:",
            "- `match_developer_to_project(developer, project, required_skills)`:",
            "  - computes skill/experience/availability/cgpa/performance sub-scores",
            "  - combines them with weights:",
            "    - skill 0.4, experience 0.2, availability 0.15, cgpa 0.15, performance 0.1",
            "  - builds `matching_skills` from exact matches or approximate matches via `are_skills_similar`",
            "  - returns a full match result dict (including `match_score` as a percentage).",
            "",
            "Recommendations:",
            "- `get_recommendations(project_id, required_skills, developers, project_complexity=50)` loops developers, filters to role 'developer', ranks, and returns top results plus `top_matches` (top 3 developer ids).",
        ],
    )

    doc.add_heading("12) Utilities", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/utils/file_handler.py` provides `save_uploaded_file`.",
            "- Builds a target directory: `upload_dir/subdir` and ensures it exists.",
            "- Generates a random filename using `uuid.uuid4().hex` plus the uploaded file extension.",
            "- Reads the uploaded content (`await upload_file.read()`) and writes it as bytes.",
            "",
            "`backend/app/utils/validators.py` contains a `PyObjectId` placeholder class (a BSON ObjectId subclass).",
            "`backend/app/utils/mongo_helpers.py` centralizes `ObjectId` conversion and query helpers used by tasks, projects, and chatbot aggregation.",
        ],
    )

    doc.add_heading("13) Teams Routes", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/teams.py` exposes `/teams` endpoints for team listing and management aligned with project `assigned_team` data.",
        ],
    )

    doc.add_heading("14) Analytics Routes", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/analytics.py` exposes `/analytics` dashboards and metrics (utilization, gaps, summaries) for managers/admins.",
        ],
    )

    doc.add_heading("15) Recommendation Flow", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/recommendation_flow.py` registers `/recommendations` routes for AI team recommendations, approval, and integration with project team fields and task creation (see `SkillMatcher` and project update logic).",
        ],
    )

    doc.add_heading("16) Chatbot (NLP)", level=1)
    add_paragraphs(
        doc,
        [
            "`backend/app/routes/chatbot.py` — `POST /chatbot/query` with JWT; loads tasks/projects/users from MongoDB, resolves bilingual response style, and calls `answer_with_context` from `app.nlp.chat_engine`.",
            "Mode is controlled by environment variable `CHATBOT_MODE` (`rules` default, `hybrid` for optional Ollama fallback).",
            "`backend/app/nlp/chat_engine.py` — rule-based intents (English and Roman Urdu patterns): deadlines, assignee tasks, team summaries with **names** (no raw hex IDs), jury-style quick answers (project lists, counts, skill ownership), and optional LLM path when configured.",
        ],
    )

    doc.add_heading("17) Operational Notes", level=1)
    add_paragraphs(
        doc,
        [
            "MongoDB `_id` fields are generally handled via `bson.ObjectId` and helpers in `mongo_helpers` / route-level checks — use consistent string ids in API paths matching stored documents.",
            "Chatbot and UI should surface **human-readable names**, not MongoDB ObjectId strings, for end users.",
            "Regenerate this document after major backend changes by running `python generate_code_explanation_doc.py` from the `backend` directory.",
        ],
    )

    out_path = "backend_code_explanation.docx"
    doc.save(out_path)
    print(f"Saved Word document: {out_path}")


if __name__ == "__main__":
    main()

